const DOM_ID_FIELDS = Object.freeze([
  ["appRoot", "app"],
  ["bootError", "boot-error"],
  ["runInfo", "run-info"],
  ["engineStatus", "engine-status"],
  ["topMetricsRoot", "top-metrics"],
  ["topMetricTokens", "top-metric-tokens"],
  ["topMetricTokensValue", "top-metric-tokens-value"],
  ["topMetricTokensSparkIn", "top-metric-tokens-spark-in"],
  ["topMetricTokensSparkOut", "top-metric-tokens-spark-out"],
  ["topMetricApiCalls", "top-metric-api-calls"],
  ["topMetricApiCallsValue", "top-metric-api-calls-value"],
  ["topMetricCost", "top-metric-cost"],
  ["topMetricCostValue", "top-metric-cost-value"],
  ["topMetricQueue", "top-metric-queue"],
  ["topMetricQueueValue", "top-metric-queue-value"],
  ["topMetricQueueTrend", "top-metric-queue-trend"],
  ["topMetricRender", "top-metric-render"],
  ["topMetricRenderValue", "top-metric-render-value"],
  ["sessionTabStrip", "session-tab-strip"],
  ["sessionTabList", "session-tab-list"],
  ["sessionTabNew", "session-tab-new"],
  ["sessionTabFork", "session-tab-fork"],
  ["sessionTabDesignReview", "session-tab-design-review"],
  ["appMenuToggle", "app-menu-toggle"],
  ["appMenu", "app-menu"],
  ["newRun", "new-run"],
  ["openRun", "open-run"],
  ["saveSession", "save-session"],
  ["closeSession", "close-session"],
  ["import", "import"],
  ["canvasImport", "canvas-import"],
  ["export", "export"],
  ["juggernautToolRail", "juggernaut-tool-rail"],
  ["juggernautSelectionStatus", "juggernaut-selection-status"],
  ["juggernautAgentRunnerOpen", "juggernaut-agent-runner-open"],
  ["juggernautExportPsd", "juggernaut-export-psd"],
  ["juggernautExportMenu", "juggernaut-export-menu"],
  ["juggernautExportFormatPsd", "juggernaut-export-format-psd"],
  ["juggernautExportFormatPng", "juggernaut-export-format-png"],
  ["juggernautExportFormatJpg", "juggernaut-export-format-jpg"],
  ["juggernautExportFormatWebp", "juggernaut-export-format-webp"],
  ["juggernautExportFormatTiff", "juggernaut-export-format-tiff"],
  ["reelAdminToggle", "reel-admin-toggle"],
  ["settingsToggle", "settings-toggle"],
  ["settingsDrawer", "settings-drawer"],
  ["settingsClose", "settings-close"],
  ["railIconPack", "rail-icon-pack"],
  ["memoryToggle", "memory-toggle"],
  ["alwaysOnVisionToggle", "always-on-vision-toggle"],
  ["alwaysOnVisionReadout", "always-on-vision-readout"],
  ["textModel", "text-model"],
  ["imageModel", "image-model"],
  ["promptStrategyMode", "prompt-strategy-mode"],
  ["promptRepeatFullToggle", "prompt-repeat-full-toggle"],
  ["promptBenchmarkReadout", "prompt-benchmark-readout"],
  ["promptBenchmarkReset", "prompt-benchmark-reset"],
  ["installTelemetryToggle", "install-telemetry-toggle"],
  ["installTelemetryStatus", "install-telemetry-status"],
  ["aestheticOnboardingStatus", "aesthetic-onboarding-status"],
  ["aestheticOnboardingOpen", "aesthetic-onboarding-open"],
  ["aestheticOnboardingClear", "aesthetic-onboarding-clear"],
  ["openrouterOnboardingStatus", "openrouter-onboarding-status"],
  ["openrouterOnboardingOpen", "openrouter-onboarding-open"],
  ["openrouterOnboardingReset", "openrouter-onboarding-reset"],
  ["openrouterApiKeyClear", "openrouter-api-key-clear"],
  ["portraitsDir", "portraits-dir"],
  ["portraitsDirPick", "portraits-dir-pick"],
  ["portraitsDirClear", "portraits-dir-clear"],
  ["keyStatus", "key-status"],
  ["motherIntentSourceIndicator", "mother-intent-source-indicator"],
  ["canvasWrap", "canvas-wrap"],
  ["dropHint", "drop-hint"],
  ["workCanvas", "work-canvas"],
  ["effectsCanvas", "effects-canvas"],
  ["imageFx", "image-fx"],
  ["imageFx2", "image-fx-2"],
  ["overlayCanvas", "overlay-canvas"],
  ["communicationShell", "communication-shell"],
  ["communicationCanvasCursor", "communication-canvas-cursor"],
  ["communicationCanvasCursorArt", "communication-canvas-cursor-art"],
  ["communicationRail", "communication-rail"],
  ["communicationToolMarker", "communication-tool-marker"],
  ["communicationToolProtect", "communication-tool-protect"],
  ["communicationToolMagicSelect", "communication-tool-magic-select"],
  ["communicationToolStamp", "communication-tool-stamp"],
  ["communicationToolMakeSpace", "communication-tool-make-space"],
  ["communicationToolEraser", "communication-tool-eraser"],
  ["communicationStampPicker", "communication-stamp-picker"],
  ["communicationStampPickerTitle", "communication-stamp-picker-title"],
  ["communicationStampPickerSubtitle", "communication-stamp-picker-subtitle"],
  ["communicationStampIntentList", "communication-stamp-intent-list"],
  ["communicationStampCustomPanel", "communication-stamp-custom-panel"],
  ["communicationStampCustomInput", "communication-stamp-custom-input"],
  ["communicationStampCustomCancel", "communication-stamp-custom-cancel"],
  ["communicationStampCustomSubmit", "communication-stamp-custom-submit"],
  ["communicationProposalTray", "communication-proposal-tray"],
  ["communicationProposalTrayClose", "communication-proposal-tray-close"],
  ["communicationProposalSlotList", "communication-proposal-slot-list"],
  ["controlStrip", "control-strip"],
  ["fileBrowserDock", "file-browser-dock"],
  ["fileBrowserHeader", "file-browser-header"],
  ["fileBrowserChoose", "file-browser-choose"],
  ["fileBrowserUp", "file-browser-up"],
  ["fileBrowserRefresh", "file-browser-refresh"],
  ["fileBrowserPath", "file-browser-path"],
  ["fileBrowserList", "file-browser-list"],
  ["annotatePanel", "annotate-panel"],
  ["annotateClose", "annotate-close"],
  ["annotateMeta", "annotate-meta"],
  ["annotateModel", "annotate-model"],
  ["annotateText", "annotate-text"],
  ["annotateCancel", "annotate-cancel"],
  ["annotateSend", "annotate-send"],
  ["promptGeneratePanel", "prompt-generate-panel"],
  ["promptGenerateClose", "prompt-generate-close"],
  ["promptGenerateMeta", "prompt-generate-meta"],
  ["promptGenerateModel", "prompt-generate-model"],
  ["promptGenerateText", "prompt-generate-text"],
  ["promptGenerateCancel", "prompt-generate-cancel"],
  ["promptGenerateSend", "prompt-generate-send"],
  ["markPanel", "mark-panel"],
  ["markTitle", "mark-title"],
  ["markClose", "mark-close"],
  ["markMeta", "mark-meta"],
  ["markText", "mark-text"],
  ["markDelete", "mark-delete"],
  ["markSave", "mark-save"],
  ["hud", "hud"],
  ["hudLineUnit", "hud-line-unit"],
  ["hudLineDirector", "hud-line-director"],
  ["hudDirectorKey", "hud-director-k"],
  ["hudDirectorVal", "hud-director-v"],
  ["hudLineDesc", "hud-line-desc"],
  ["hudLineSel", "hud-line-sel"],
  ["hudUnitName", "hud-unit-name"],
  ["hudUnitDesc", "hud-unit-desc"],
  ["hudUnitSel", "hud-unit-sel"],
  ["filmstrip", "filmstrip"],
  ["spawnbar", "spawnbar"],
  ["toast", "toast"],
  ["agentsDock", "agents-dock"],
  ["portraitDock", "portrait-dock"],
  ["agentSlotPrimary", "agent-slot-primary"],
  ["agentSlotSecondary", "agent-slot-secondary"],
  ["portraitTitle", "portrait-title"],
  ["portraitAvatar", "portrait-avatar"],
  ["portraitVideo", "portrait-video"],
  ["portraitTitle2", "portrait-title-2"],
  ["portraitAvatar2", "portrait-avatar-2"],
  ["portraitVideo2", "portrait-video-2"],
  ["selectionMeta", "selection-meta"],
  ["motherState", "mother-state"],
  ["motherRolePreview", "mother-role-preview"],
  ["tipsText", "tips-text"],
  ["motherOverlay", "mother-overlay"],
  ["motherPanelStack", "mother-panel-stack"],
  ["motherPanel", "mother-panel"],
  ["motherRefineToggle", "mother-refine-toggle"],
  ["motherAdvanced", "mother-advanced"],
  ["motherTransformationMode", "mother-transformation-mode"],
  ["motherRoleSubject", "mother-role-subject"],
  ["motherRoleModel", "mother-role-model"],
  ["motherRoleMediator", "mother-role-mediator"],
  ["motherRoleObject", "mother-role-object"],
  ["motherAvatar", "mother-avatar"],
  ["motherVideo", "mother-video"],
  ["motherAbilityIcon", "mother-ability-icon"],
  ["motherConfirm", "mother-confirm"],
  ["motherStop", "mother-stop"],
  ["canvasMoodStatus", "canvas-mood-status"],
  ["motherMoodToggle", "mother-mood-toggle"],
  ["motherMoodMenu", "mother-mood-menu"],
  ["customToolDock", "custom-tool-dock"],
  ["actionGrid", "action-grid"],
  ["createToolPanel", "create-tool-panel"],
  ["createToolClose", "create-tool-close"],
  ["createToolMeta", "create-tool-meta"],
  ["createToolName", "create-tool-name"],
  ["createToolText", "create-tool-text"],
  ["createToolPreview", "create-tool-preview"],
  ["createToolCancel", "create-tool-cancel"],
  ["createToolSave", "create-tool-save"],
  ["agentRunnerPanel", "agent-runner-panel"],
  ["agentRunnerExpand", "agent-runner-expand"],
  ["agentRunnerClose", "agent-runner-close"],
  ["agentRunnerMeta", "agent-runner-meta"],
  ["agentRunnerPlanner", "agent-runner-planner"],
  ["agentRunnerMaxSteps", "agent-runner-max-steps"],
  ["agentRunnerGoal", "agent-runner-goal"],
  ["agentRunnerSubmit", "agent-runner-submit"],
  ["agentRunnerPlan", "agent-runner-plan"],
  ["agentRunnerScore", "agent-runner-score"],
  ["agentRunnerLog", "agent-runner-log"],
  ["agentRunnerCopy", "agent-runner-copy"],
  ["agentRunnerClear", "agent-runner-clear"],
  ["agentRunnerStep", "agent-runner-step"],
  ["agentRunnerAuto", "agent-runner-auto"],
  ["agentRunnerStop", "agent-runner-stop"],
  ["agentRunnerBanner", "agent-runner-banner"],
  ["agentRunnerBannerMode", "agent-runner-banner-mode"],
  ["agentRunnerBannerStep", "agent-runner-banner-step"],
  ["agentRunnerBannerSummary", "agent-runner-banner-summary"],
  ["agentRunnerBannerDetail", "agent-runner-banner-detail"],
  ["agentRunnerBannerShow", "agent-runner-banner-show"],
  ["agentRunnerBannerStop", "agent-runner-banner-stop"],
  ["imageMenu", "image-menu"],
  ["motherWheelMenu", "mother-wheel-menu"],
  ["quickActions", "quick-actions"],
  ["timelineDock", "timeline-dock"],
  ["timelineShell", "timeline-shell"],
  ["timelineToggle", "timeline-toggle"],
  ["timelineToggleLabel", "timeline-toggle-label"],
  ["timelineToggleSummary", "timeline-toggle-summary"],
  ["timelineBody", "timeline-body"],
  ["timelinePrev", "timeline-prev"],
  ["timelineNext", "timeline-next"],
  ["timelineStrip", "timeline-strip"],
  ["timelineDetail", "timeline-detail"],
  ["openrouterOnboardingModal", "openrouter-onboarding-modal"],
  ["openrouterOnboardingHeader", "openrouter-onboarding-header"],
  ["openrouterOnboardingTitle", "openrouter-onboarding-title"],
  ["openrouterOnboardingSubtitle", "openrouter-onboarding-subtitle"],
  ["openrouterOnboardingProgress", "openrouter-onboarding-progress"],
  ["openrouterOnboardingBody", "openrouter-onboarding-body"],
  ["openrouterOnboardingClose", "openrouter-onboarding-close"],
  ["openrouterOnboardingBack", "openrouter-onboarding-back"],
  ["openrouterOnboardingSkip", "openrouter-onboarding-skip"],
  ["openrouterOnboardingNext", "openrouter-onboarding-next"],
  ["openrouterOnboardingMediaVideo", "openrouter-onboarding-media-video"],
  ["aestheticOnboardingModal", "aesthetic-onboarding-modal"],
  ["aestheticOnboardingTitle", "aesthetic-onboarding-title"],
  ["aestheticOnboardingSubtitle", "aesthetic-onboarding-subtitle"],
  ["aestheticOnboardingProgress", "aesthetic-onboarding-progress"],
  ["aestheticOnboardingBody", "aesthetic-onboarding-body"],
  ["aestheticOnboardingClose", "aesthetic-onboarding-close"],
  ["aestheticOnboardingBack", "aesthetic-onboarding-back"],
  ["aestheticOnboardingSkip", "aesthetic-onboarding-skip"],
  ["aestheticOnboardingNext", "aesthetic-onboarding-next"],
]);

const DOM_QUERY_FIELDS = Object.freeze([["brandStrip", ".brand-strip"]]);
const DOM_MUTABLE_NULL_FIELDS = Object.freeze(["runtimePinAssistantToggle", "runtimeDiagnosticsToggle"]);

export const CANVAS_APP_REQUIRED_BOOT_FIELDS = Object.freeze([
  "appRoot",
  "brandStrip",
  "sessionTabList",
  "sessionTabNew",
  "sessionTabFork",
  "canvasWrap",
  "dropHint",
  "workCanvas",
  "effectsCanvas",
  "overlayCanvas",
  "actionGrid",
  "timelineDock",
  "toast",
]);

export function createCanvasAppDom(documentObj = globalThis.document) {
  const doc = documentObj && typeof documentObj.getElementById === "function" ? documentObj : null;
  const dom = {};
  for (const [key, id] of DOM_ID_FIELDS) {
    dom[key] = doc ? doc.getElementById(id) : null;
  }
  for (const [key, selector] of DOM_QUERY_FIELDS) {
    dom[key] = doc && typeof doc.querySelector === "function" ? doc.querySelector(selector) : null;
  }
  for (const key of DOM_MUTABLE_NULL_FIELDS) {
    dom[key] = null;
  }
  return dom;
}

export function validateCanvasAppBootDom(dom = {}, requiredFields = CANVAS_APP_REQUIRED_BOOT_FIELDS) {
  const missing = [];
  for (const key of requiredFields) {
    if (dom?.[key]) continue;
    missing.push(key);
  }
  if (missing.length) {
    throw new Error(`Cue canvas boot missing required DOM nodes: ${missing.join(", ")}`);
  }
  return dom;
}
