import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, "..", "src", "index.html"), "utf8");
const css = readFileSync(join(here, "..", "src", "styles.css"), "utf8");
const tauriConfig = readFileSync(join(here, "..", "src-tauri", "tauri.conf.json"), "utf8");

test("startup boot overlay points at the local Desktop MP4 and gates reveal until boot finishes", () => {
  assert.match(html, /id="boot-video-overlay"/);
  assert.match(html, /id="boot-video-player"/);
  assert.match(html, /class="boot-video-status-rail"/);
  assert.match(html, /class="boot-video-status-label">Loading</);
  assert.match(html, /id="boot-video-progress-bar"/);
  assert.match(html, /<body class="juggernaut-shell boot-pending">/);
  assert.match(html, /html,\s*body\s*\{\s*background: #efe7d7;/);
  assert.match(html, /const LOCAL_BOOT_VIDEO_PATH = "\/Users\/mainframe\/Desktop\/load\.mp4";/);
  assert.match(html, /const LOCAL_BOOT_VIDEO_SESSION_KEY = "juggernaut\.localBootVideoShown";/);
  assert.match(html, /const BOOT_VIDEO_MAX_HOLD_MS = 20000;/);
  assert.match(html, /const BOOT_SHELL_INTRO_DELAY_MS = 60;/);
  assert.match(html, /const BOOT_VIDEO_START_DELAY_MS = 2000;/);
  assert.match(html, /const BOOT_STATUS_TICK_MS = 700;/);
  assert.match(html, /const SPLASH_WINDOW_SIZE = 620;/);
  assert.match(html, /const APP_WINDOW_WIDTH = 1400;/);
  assert.match(html, /const APP_WINDOW_HEIGHT = 900;/);
  assert.match(html, /const bootProgressBarEl = document\.getElementById\("boot-video-progress-bar"\);/);
  assert.match(html, /function setBootProgress\(progress = 0\)/);
  assert.match(html, /function startBootPrepStatusCycle\(\)/);
  assert.match(html, /window\.setInterval\(\(\) => \{/);
  assert.match(html, /const bytes = await readBinaryFile\(LOCAL_BOOT_VIDEO_PATH\);/);
  assert.match(html, /await new Promise\(\(resolve\) => \{\s*window\.setTimeout\(resolve, BOOT_VIDEO_START_DELAY_MS\);/);
  assert.match(html, /bootVideoObjectUrl = URL\.createObjectURL\(new Blob\(\[bytes\], \{ type: "video\/mp4" \}\)\);/);
  assert.match(html, /bootOverlayEl\?\.classList\.add\("is-video-ready"\);/);
  assert.match(html, /bootOverlayEl\.classList\.add\("is-shell-visible"\);/);
  assert.match(html, /bootVideoEl\.classList\.add\("is-visible"\);/);
  assert.match(html, /bodyEl\?\.classList\.add\("is-boot-revealed"\);/);
  assert.match(html, /armBootShellIntro\(\);/);
  assert.match(html, /startBootPrepStatusCycle\(\);/);
  assert.match(html, /stopBootPrepStatusCycle\(\);/);
  assert.match(html, /await appWindow\.setSize\(new LogicalSize\(width, height\)\);/);
  assert.match(html, /await appWindow\.center\(\);/);
  assert.match(html, /await resizeWindow\(SPLASH_WINDOW_SIZE, SPLASH_WINDOW_SIZE\);/);
  assert.match(html, /await resizeWindow\(APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT\);/);
  assert.match(html, /bootReady = true;/);
  assert.match(html, /bootVideoDone = true;/);
  assert.match(html, /let bootRevealStarted = false;/);
  assert.match(html, /if \(bootRevealStarted\) return;/);
  assert.match(html, /bootRevealStarted = true;/);
  assert.match(html, /enterSplashWindowMode\(\);/);
  assert.match(html, /maybeRevealApp\(\);/);
  assert.match(html, /hideBootOverlay\(\);/);
  assert.match(html, /if \(!bootVideoDone\) setBootStatus\("Workspace ready\. Waiting on video…", 90\);\s*maybeRevealApp\(\);/);
  assert.match(tauriConfig, /"width": 620,/);
  assert.match(tauriConfig, /"height": 620,/);
  assert.match(tauriConfig, /"center": true,/);
});

test("startup boot overlay has fullscreen video treatment and fade-out dismissal", () => {
  assert.match(css, /\.boot-video-overlay\s*\{/);
  assert.match(css, /position: fixed;/);
  assert.match(css, /z-index: 20000;/);
  assert.match(css, /background:\s*#efe7d7;/);
  assert.match(css, /opacity:\s*1;/);
  assert.match(css, /transform:\s*none;/);
  assert.match(css, /\.boot-video-overlay\.is-shell-visible\s*\{/);
  assert.match(css, /\.boot-video-overlay\.is-dismissed\s*\{/);
  assert.match(css, /\.boot-video-player\s*\{/);
  assert.match(css, /width: auto;/);
  assert.match(css, /height: auto;/);
  assert.match(css, /max-width: 100vw;/);
  assert.match(css, /max-height: 100vh;/);
  assert.match(css, /\.boot-video-overlay\.is-video-ready \.boot-video-player,\s*\.boot-video-player\.is-visible\s*\{/);
  assert.match(css, /\.boot-video-copy\s*\{/);
  assert.match(css, /\.boot-video-status-rail\s*\{/);
  assert.match(css, /bottom:\s*22px;/);
  assert.match(css, /\.boot-video-overlay\.is-shell-visible \.boot-video-status-rail\s*\{/);
  assert.match(css, /\.boot-video-status-label\s*\{/);
  assert.match(css, /\.boot-video-progress-bar\s*\{/);
  assert.match(css, /\.boot-video-overlay\.is-shell-visible \.boot-video-copy\s*\{/);
  assert.match(css, /\.boot-video-overlay\.is-video-ready \.boot-video-copy\s*\{/);
  assert.match(css, /\.boot-video-logo\s*\{\s*display:\s*none;/);
  assert.match(css, /\.boot-video-mark\s*\{/);
  assert.match(css, /font-family:\s*"Syne", "Space Grotesk", sans-serif;/);
  assert.match(css, /font-weight:\s*800;/);
  assert.match(css, /color:\s*#050505;/);
  assert.match(css, /\.boot-video-status\s*\{/);
  assert.match(css, /font-family:\s*"IBM Plex Mono", monospace;/);
  assert.match(css, /body\.is-boot-revealed #app\s*\{/);
});
