#!/usr/bin/env node

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  JUGGERNAUT_RAIL_ICON_BLUEPRINTS,
  JUGGERNAUT_RAIL_ICON_STYLE,
  renderJuggernautRailIconSvg,
} from "../desktop/src/juggernaut_shell/rail_icon_blueprint.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = dirname(here);
const assetDir = join(root, "desktop", "src", "assets", "juggernaut-rail-icons");
const generatedDir = join(root, "desktop", "src", "juggernaut_shell", "generated");
const registryPath = join(generatedDir, "rail_icon_registry.js");
const manifestPath = join(assetDir, "manifest.json");

function renderRegistryModule(entries) {
  const lines = [];
  lines.push("// Generated by scripts/generate_juggernaut_rail_icons.mjs");
  lines.push("");
  lines.push("export const JUGGERNAUT_RAIL_ICON_REGISTRY = Object.freeze({");
  for (const [toolId, svg] of entries) {
    lines.push(`  ${JSON.stringify(toolId)}: ${JSON.stringify(svg)},`);
  }
  lines.push("});");
  lines.push("");
  lines.push("export function getJuggernautRailIconSvg(toolId = \"\") {");
  lines.push("  return JUGGERNAUT_RAIL_ICON_REGISTRY[String(toolId || \"\").trim()] || \"\";");
  lines.push("}");
  lines.push("");
  return `${lines.join("\n")}\n`;
}

async function main() {
  await mkdir(assetDir, { recursive: true });
  await mkdir(generatedDir, { recursive: true });

  const manifestIcons = [];
  const registryEntries = [];

  for (const blueprint of JUGGERNAUT_RAIL_ICON_BLUEPRINTS) {
    const svg = renderJuggernautRailIconSvg(blueprint);
    const svgPath = join(assetDir, `${blueprint.toolId}.svg`);
    await writeFile(svgPath, `${svg}\n`, "utf8");
    manifestIcons.push({
      tool_id: blueprint.toolId,
      label: blueprint.label,
      semantic_role: blueprint.semanticRole,
      notes: blueprint.notes,
      asset: `./${blueprint.toolId}.svg`,
    });
    registryEntries.push([blueprint.toolId, svg]);
  }

  const manifest = {
    schema: "juggernaut.rail_icon_manifest.v1",
    generator: "scripts/generate_juggernaut_rail_icons.mjs",
    style: JUGGERNAUT_RAIL_ICON_STYLE,
    icons: manifestIcons,
  };

  await writeFile(registryPath, renderRegistryModule(registryEntries), "utf8");
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

main().catch((error) => {
  console.error("Failed to generate Juggernaut rail icons:", error);
  process.exitCode = 1;
});
