#!/usr/bin/env node

import { execFile as execFileCallback } from "node:child_process";
import { copyFile, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

import { JUGGERNAUT_RAIL_ICON_BLUEPRINTS, JUGGERNAUT_RAIL_ICON_STYLE } from "../desktop/src/juggernaut_shell/rail_icon_blueprint.js";
import {
  DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID,
  JUGGERNAUT_RAIL_ICON_PACKS,
  buildJuggernautRailIconGeminiPrompt,
} from "../desktop/src/juggernaut_shell/rail_icon_packs.js";

const execFile = promisify(execFileCallback);
const here = dirname(fileURLToPath(import.meta.url));
const root = dirname(here);
const assetDir = join(root, "desktop", "src", "assets", "juggernaut-rail-icons");
const generatedDir = join(root, "desktop", "src", "juggernaut_shell", "generated");
const registryPath = join(generatedDir, "rail_icon_registry.js");
const manifestPath = join(assetDir, "manifest.json");
const tempDir = join(root, ".tmp", "juggernaut-rail-icons");
const planPath = join(tempDir, "generation-plan.json");
const reportPath = join(tempDir, "generation-report.json");
const pythonGeneratorPath = join(root, "scripts", "generate_juggernaut_rail_icons.py");
const ALL_BLUEPRINT_TOOL_IDS = new Set(JUGGERNAUT_RAIL_ICON_BLUEPRINTS.map((blueprint) => blueprint.toolId));
const GENERATED_ICON_PACKS = JUGGERNAUT_RAIL_ICON_PACKS.filter((pack) => pack.generated !== false);
const GENERATED_DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID =
  GENERATED_ICON_PACKS[0]?.id || DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID;

function parseCliArgs(argv = process.argv.slice(2)) {
  const args = Array.from(argv);
  const options = {
    onlyToolIds: null,
    onlyPackIds: null,
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = String(args[index] || "").trim();
    if (!arg) continue;
    if (arg === "--only") {
      const raw = String(args[index + 1] || "").trim();
      if (!raw) {
        throw new Error("--only requires a comma-separated tool id list");
      }
      options.onlyToolIds = raw.split(",").map((value) => String(value || "").trim()).filter(Boolean);
      index += 1;
      continue;
    }
    if (arg.startsWith("--only=")) {
      options.onlyToolIds = arg
        .slice("--only=".length)
        .split(",")
        .map((value) => String(value || "").trim())
        .filter(Boolean);
      continue;
    }
    if (arg === "--packs" || arg === "--pack") {
      const raw = String(args[index + 1] || "").trim();
      if (!raw) {
        throw new Error("--packs requires a comma-separated pack id list");
      }
      options.onlyPackIds = raw.split(",").map((value) => String(value || "").trim()).filter(Boolean);
      index += 1;
      continue;
    }
    if (arg.startsWith("--packs=") || arg.startsWith("--pack=")) {
      const raw = arg.includes("--packs=") ? arg.slice("--packs=".length) : arg.slice("--pack=".length);
      options.onlyPackIds = raw
        .split(",")
        .map((value) => String(value || "").trim())
        .filter(Boolean);
      continue;
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  return options;
}

const cli = parseCliArgs();
const requestedToolIdSet = cli.onlyToolIds ? new Set(cli.onlyToolIds) : null;
const requestedPackIdSet = cli.onlyPackIds ? new Set(cli.onlyPackIds) : null;
const ACTIVE_ICON_PACKS = requestedPackIdSet
  ? GENERATED_ICON_PACKS.filter((pack) => requestedPackIdSet.has(pack.id))
  : GENERATED_ICON_PACKS;
const ACTIVE_ICON_BLUEPRINTS = requestedToolIdSet
  ? JUGGERNAUT_RAIL_ICON_BLUEPRINTS.filter((blueprint) => requestedToolIdSet.has(blueprint.toolId))
  : JUGGERNAUT_RAIL_ICON_BLUEPRINTS;

if (requestedPackIdSet && ACTIVE_ICON_PACKS.length !== requestedPackIdSet.size) {
  const knownPackIds = new Set(GENERATED_ICON_PACKS.map((pack) => pack.id));
  const unknownPackIds = Array.from(requestedPackIdSet).filter((packId) => !knownPackIds.has(packId));
  throw new Error(`Unknown pack ids for --packs: ${unknownPackIds.join(", ")}`);
}

if (requestedToolIdSet && ACTIVE_ICON_BLUEPRINTS.length !== requestedToolIdSet.size) {
  const knownToolIds = new Set(JUGGERNAUT_RAIL_ICON_BLUEPRINTS.map((blueprint) => blueprint.toolId));
  const unknownToolIds = Array.from(requestedToolIdSet).filter((toolId) => !knownToolIds.has(toolId));
  throw new Error(`Unknown tool ids for --only: ${unknownToolIds.join(", ")}`);
}

const PARTIAL_GENERATION =
  ACTIVE_ICON_BLUEPRINTS.length !== JUGGERNAUT_RAIL_ICON_BLUEPRINTS.length ||
  ACTIVE_ICON_PACKS.length !== GENERATED_ICON_PACKS.length;

function renderRegistryModule(entriesByPack) {
  const lines = [];
  lines.push("// Generated by scripts/generate_juggernaut_rail_icons.mjs");
  lines.push("");
  lines.push(
    `export const DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID = ${JSON.stringify(GENERATED_DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID)};`
  );
  lines.push("");
  lines.push("function normalizePackId(value = \"\") {");
  lines.push("  return String(value || \"\").trim() || DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID;");
  lines.push("}");
  lines.push("");
  lines.push("function escapeCssUrl(value = \"\") {");
  lines.push("  return String(value || \"\").replace(/'/g, \"%27\");");
  lines.push("}");
  lines.push("");
  lines.push("export const JUGGERNAUT_RAIL_ICON_PACK_ASSET_URLS = Object.freeze({");
  for (const [packId, entries] of entriesByPack) {
    lines.push(`  ${JSON.stringify(packId)}: Object.freeze({`);
    for (const [toolId, relativeAssetPath] of entries) {
      lines.push(`    ${JSON.stringify(toolId)}: new URL(${JSON.stringify(relativeAssetPath)}, import.meta.url).href,`);
    }
    lines.push("  }),");
  }
  lines.push("});");
  lines.push("");
  lines.push(
    "export const JUGGERNAUT_RAIL_ICON_ASSET_URLS = JUGGERNAUT_RAIL_ICON_PACK_ASSET_URLS[DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID];"
  );
  lines.push("");
  lines.push("export function getJuggernautRailIconAssetUrl(toolId = \"\", packId = DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID) {");
  lines.push("  const normalizedToolId = String(toolId || \"\").trim();");
  lines.push("  const normalizedPackId = normalizePackId(packId);");
  lines.push(
    "  const pack = JUGGERNAUT_RAIL_ICON_PACK_ASSET_URLS[normalizedPackId] || JUGGERNAUT_RAIL_ICON_PACK_ASSET_URLS[DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID] || {};"
  );
  lines.push("  return pack[normalizedToolId] || JUGGERNAUT_RAIL_ICON_ASSET_URLS[normalizedToolId] || \"\";");
  lines.push("}");
  lines.push("");
  lines.push("export function getJuggernautRailIconMarkup(toolId = \"\", packId = DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID) {");
  lines.push("  const normalizedToolId = String(toolId || \"\").trim();");
  lines.push("  const normalizedPackId = normalizePackId(packId);");
  lines.push("  const assetUrl = getJuggernautRailIconAssetUrl(normalizedToolId, normalizedPackId);");
  lines.push("  if (!assetUrl) return \"\";");
  lines.push("  const toolClass = `tool-icon-${normalizedToolId.replace(/_/g, \"-\")}`;");
  lines.push("  const packClass = `tool-icon-pack-${normalizedPackId.replace(/_/g, \"-\")}`;");
  lines.push(
    "  return `<span class=\"tool-icon tool-icon-mask ${toolClass} ${packClass}\" aria-hidden=\"true\" style=\"--tool-icon-mask:url('${escapeCssUrl(assetUrl)}')\"></span>`;"
  );
  lines.push("}");
  lines.push("");
  return `${lines.join("\n")}\n`;
}

function buildGenerationPlan() {
  return {
    schema: "juggernaut.rail_icon_generation_plan.v1",
    generator: "scripts/generate_juggernaut_rail_icons.mjs",
    provider: {
      name: "gemini",
      model: process.env.GEMINI_IMAGE_MODEL || process.env.OSCILLO_GOOGLE_IMAGE_MODEL || "gemini-3-pro-image-preview",
    },
    default_pack_id: GENERATED_DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID,
    packs: ACTIVE_ICON_PACKS.map((pack) => ({
      id: pack.id,
      label: pack.label,
      settings_label: pack.settingsLabel,
      menu_label: pack.menuLabel,
      description: pack.description,
      prompt_style: pack.promptStyle,
      icons: ACTIVE_ICON_BLUEPRINTS.map((blueprint) => ({
        tool_id: blueprint.toolId,
        label: blueprint.label,
        semantic_role: blueprint.semanticRole,
        notes: blueprint.notes,
        gemini_prompt: buildJuggernautRailIconGeminiPrompt(blueprint, pack.id),
      })),
    })),
  };
}

function readAssetToolId(fileName = "") {
  const match = String(fileName || "").match(/^(.+)\.(png|svg)$/i);
  return match ? String(match[1] || "").trim() : "";
}

async function pruneStaleAssetFiles(dirPath, allowedToolIds = ALL_BLUEPRINT_TOOL_IDS) {
  let entries = [];
  try {
    entries = await readdir(dirPath, { withFileTypes: true });
  } catch {
    return;
  }
  await Promise.all(
    entries.map(async (entry) => {
      if (!entry?.isFile?.()) return;
      const toolId = readAssetToolId(entry.name);
      if (!toolId || allowedToolIds.has(toolId)) return;
      await rm(join(dirPath, entry.name), { force: true });
    })
  );
}

function findPackReport(report, packId) {
  return (report?.packs || []).find((pack) => pack.id === packId) || null;
}

function findIconReport(packReport, toolId) {
  return (packReport?.icons || []).find((icon) => icon.tool_id === toolId) || null;
}

async function readExistingManifest() {
  try {
    return JSON.parse(await readFile(manifestPath, "utf8"));
  } catch {
    return null;
  }
}

async function main() {
  await mkdir(assetDir, { recursive: true });
  await mkdir(generatedDir, { recursive: true });
  await mkdir(tempDir, { recursive: true });
  await pruneStaleAssetFiles(assetDir);
  await Promise.all(GENERATED_ICON_PACKS.map((pack) => pruneStaleAssetFiles(join(assetDir, pack.id))));

  const existingManifest = PARTIAL_GENERATION ? await readExistingManifest() : null;
  if (PARTIAL_GENERATION && !existingManifest) {
    throw new Error("Partial icon generation requires an existing manifest.json to merge against");
  }

  const plan = buildGenerationPlan();
  await writeFile(planPath, `${JSON.stringify(plan, null, 2)}\n`, "utf8");

  const pythonCommand = process.env.PYTHON || "python";
  const reportParts = await Promise.all(
    plan.packs.map(async (pack) => {
      const packPlanPath = join(tempDir, `generation-plan-${pack.id}.json`);
      const packReportPath = join(tempDir, `generation-report-${pack.id}.json`);
      const packPlan = {
        ...plan,
        packs: [pack],
      };
      await writeFile(packPlanPath, `${JSON.stringify(packPlan, null, 2)}\n`, "utf8");
      await execFile(pythonCommand, [
        pythonGeneratorPath,
        "--plan",
        packPlanPath,
        "--report",
        packReportPath,
        "--asset-dir",
        assetDir,
      ]);
      return JSON.parse(await readFile(packReportPath, "utf8"));
    })
  );
  const report = {
    schema: "juggernaut.rail_icon_generation_report.v1",
    generator: "scripts/generate_juggernaut_rail_icons.mjs",
    provider: reportParts[0]?.provider || null,
    packs: reportParts.flatMap((part) => part?.packs || []),
  };
  await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
  const registryEntriesByPack = [];
  const manifestPacks = [];
  let defaultManifestIcons = [];

  for (const pack of GENERATED_ICON_PACKS) {
    const packReport = findPackReport(report, pack.id);
    const existingPackEntry = (existingManifest?.packs || []).find((entry) => entry.id === pack.id) || null;
    if (!packReport && !existingPackEntry) {
      throw new Error(`Missing generation report for pack ${pack.id}`);
    }
    const packRegistryEntries = [];
    const generatedManifestIcons = new Map();
    const existingManifestIcons = new Map((existingPackEntry?.icons || []).map((icon) => [icon.tool_id, icon]));

    if (packReport) {
      for (const blueprint of ACTIVE_ICON_BLUEPRINTS) {
        const iconReport = findIconReport(packReport, blueprint.toolId);
        if (!iconReport) {
          throw new Error(`Missing generation report for ${pack.id}:${blueprint.toolId}`);
        }

        const defaultRelativeAsset = `./${blueprint.toolId}.png`;
        if (pack.id === GENERATED_DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID) {
          await copyFile(join(assetDir, pack.id, `${blueprint.toolId}.png`), join(assetDir, `${blueprint.toolId}.png`));
        }

        generatedManifestIcons.set(blueprint.toolId, {
          tool_id: blueprint.toolId,
          label: blueprint.label,
          semantic_role: blueprint.semanticRole,
          notes: blueprint.notes,
          asset:
            pack.id === GENERATED_DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID
              ? defaultRelativeAsset
              : `./${pack.id}/${blueprint.toolId}.png`,
          asset_kind: "mask_png",
          gemini_prompt: buildJuggernautRailIconGeminiPrompt(blueprint, pack.id),
          effective_prompt: iconReport.effective_prompt,
          generation: {
            raw_result_format: iconReport.raw_result_format,
            mask_strategy: iconReport.mask_strategy,
            mask_threshold: iconReport.mask_threshold,
            mask_coverage: iconReport.mask_coverage,
            mask_bbox: iconReport.mask_bbox,
            final_asset: iconReport.final_asset,
            session_index: iconReport.session_index,
          },
        });
      }
    }

    const packManifestIcons = [];
    for (const blueprint of JUGGERNAUT_RAIL_ICON_BLUEPRINTS) {
      const mergedEntry = generatedManifestIcons.get(blueprint.toolId) || existingManifestIcons.get(blueprint.toolId);
      if (!mergedEntry) {
        throw new Error(`Missing manifest metadata for ${pack.id}:${blueprint.toolId}`);
      }
      packRegistryEntries.push([blueprint.toolId, `../../assets/juggernaut-rail-icons/${pack.id}/${blueprint.toolId}.png`]);
      packManifestIcons.push(mergedEntry);
    }

    if (pack.id === GENERATED_DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID) {
      defaultManifestIcons = packManifestIcons.slice();
    }

    registryEntriesByPack.push([pack.id, packRegistryEntries]);
    manifestPacks.push({
      id: pack.id,
      label: pack.label,
      settings_label: pack.settingsLabel,
      menu_label: pack.menuLabel,
      description: pack.description,
      prompt_style: pack.promptStyle,
      icons: packManifestIcons,
    });
  }

  const manifest = {
    schema: "juggernaut.rail_icon_manifest.v3",
    generator: "scripts/generate_juggernaut_rail_icons.mjs",
    style: JUGGERNAUT_RAIL_ICON_STYLE,
    default_pack_id: GENERATED_DEFAULT_JUGGERNAUT_RAIL_ICON_PACK_ID,
    provider: report.provider || existingManifest?.provider || null,
    icons: defaultManifestIcons,
    packs: manifestPacks,
  };

  await writeFile(registryPath, renderRegistryModule(registryEntriesByPack), "utf8");
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

main().catch((error) => {
  console.error("Failed to generate Cue rail icons:", error);
  process.exitCode = 1;
});
